{{- if .Values.events.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: {{ include "static-site.eventSourceName" . }}
  namespace: {{ include "static-site.eventsNamespace" . }}
  labels:
    {{- include "static-site.labels" . | nindent 4 }}
spec:
  eventBusName: {{ .Values.events.eventBusName }}
  template:
    serviceAccountName: {{ include "static-site.eventsServiceAccountName" . }}
  dependencies:
    - name: github-push
      eventSourceName: {{ include "static-site.eventSourceName" . }}
      eventName: push
      filters:
        data:
          - path: headers.X-Github-Event
            type: string
            value:
              - push
          - path: body.ref
            type: string
            value:
              - {{ printf "refs/heads/%s" .Values.events.github.branch | quote }}
  triggers:
    - template:
        name: build-site
        k8s:
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: {{ printf "%s-" (include "static-site.workflowTemplateName" .) | trunc 58 | trimSuffix "-" }}-
                namespace: {{ .Release.Namespace }}
                labels:
                  {{- include "static-site.selectorLabels" . | nindent 18 }}
              spec:
                workflowTemplateRef:
                  name: {{ include "static-site.workflowTemplateName" . }}
                arguments:
                  parameters:
                    - name: revision
                      value: {{ .Values.site.revision | quote }}
          parameters:
            - src:
                dependencyName: github-push
                dataKey: body.after
              dest: spec.arguments.parameters.0.value
      retryStrategy:
        steps: 3
{{- end }}
